# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7cae85a17083348945d403514ba18ee71db2015bb10a6e548f2c5f27cecea09ea7ec7ec139c49c3de1627132eebdf9819eaa58eb0faddc4db0322588690aee04

test:
  secret_key_base: 82d09ccb7d7ce92a514f15505f09d94d04571e43d51f0b8ed49becf3796a2106fb3e734c7a7737bb9ec74a274c58c7742c485f5e04663faecc503bc9c667a1af

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
